version: '3'
services:
  backend:
    env_file: .env
    build: 
      context: .
      dockerfile: dockerfile
    container_name: practice-leetcode
    image: ronniesong0809/practice-leetcode
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 5000:5000
