version: '3'
services:
  app: 
    env_file: .env
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: pratice-leetcode
    restart: always
    ports: 
      - 3000:3000
    volumes:
      - ./app
    working_dir: /app
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express:0.54
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
  redis:
    image: redis
    command: --loglevel verbose
    ports:
      - 6379:6379
  redis-admin:
    image: erikdubbelboer/phpredisadmin
    ports:
      - 8085:80
    depends_on:
      - redis
    environment:
      REDIS_1_HOST: redis
      REDIS_1_NAME: redis
      REDIS_1_PORT: 6379